# yaml-language-server: $schema=https://json.schemastore.org/dependabot-2.0.json
---
version: 2

updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: ":dependabot: :package: chore(deps)"
      include: scope
    groups:
      cargo:
        update-types:
          - patch

  - package-ecosystem: rust-toolchain
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: ":dependabot: :crab: chore(deps)"
      include: scope

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: ":dependabot: :rocket: chore(deps)"
      include: scope
    groups:
      actions:
        update-types:
          - minor
          - patch
