include = ["**/*.toml"]

[formatting]
  # Align entries vertically. Entries that have table headers, comments,
  # or blank lines between them are not aligned (default: false)
  align_entries = true

  # The maximum amount of consecutive blank lines allowed (default: 2)
  allowed_blank_lines = 1

  # Target maximum column width after which arrays are expanded into new lines (default: 80)
  column_width = 100

  # Indent subtables if they come in order (default: false)
  indent_tables = true

  # Indent entries under tables (default: false)
  indent_entries = true

  # Alphabetically reorder keys that are not separated by blank lines (default: false)
  reorder_keys = true

  # Alphabetically reorder array values that are not separated by blank lines (default: false)
  reorder_arrays = true

  # Alphabetically reorder inline tables (default: false)
  reorder_inline_tables = true
